apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: example
  namespace: aaatest
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: personal
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: example
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: example-
      labels:
        build.appstudio.openshift.io/application: personal
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: example
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: aaatest
    spec:
      params:
      - name: git-url
        value: https://github.com/albarbaro/simple-nodejs-app
      - name: output-image
        value: quay.io/redhat-appstudio-qe/test-images-protected:aaatest-example-$(tt.params.git-revision)
      - name: dockerfile
        value: https://raw.githubusercontent.com/nodeshift-starters/devfile-sample/main/Dockerfile
      - name: path-context
        value: ./
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:13f5d9c921b3f727684a00084037f673a0dc4273
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: example/$(tt.params.git-revision)
    status: {}
status: {}
