apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-2
    app.kubernetes.io/part-of: personal
  name: nodejs-2
  namespace: aaatest
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nodejs-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: nodejs-2
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images-protected:aaatest-nodejs-2
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 3001
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 3001
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
