apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-2
    app.kubernetes.io/part-of: personal
  name: nodejs-2
  namespace: aaatest
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: nodejs-2
status:
  loadBalancer: {}
